name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET 
    - name: Install .NET Core 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Install .NET Core 8.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    # Build
    - name: Build
      run: ./build.ps1 --Target Pack
    
    - name: InstallGitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
      
    - name: UploadArtifacts
      uses: actions/upload-artifact@v4
      with: 
          name: VncScreenShare_${{ steps.gitversion.outputs.FullSemVer }}
          path:  artifacts/*
